#
# Makefile 
#
# Type  make    to compile all the programs
# in the chapter 
#

all: 		p15-count \
		p17-writeafterend \
		p19-readwriteclose \
		p21-buffeffect \
		p25-filecontrol \
		p27-dupdup2 \
		p33-samplestat \
		p36-openreadclosedir \
		p38-morewithls \

clean: 
	rm -f 	p04-errors_demo \
		p09-createfile \
		p15-count \
		p17-writeafterend \
		p19-readwriteclose \
		p21-buffeffect \
		p25-filecontrol \
		p27-dupdup2 \
		p33-samplestat \
		p36-openreadclosedir \
		p38-morewithls \


p09-createfile: p09-createfile.c
	gcc -g p09-createfile.c -o p09-createfile

p15-count: p15-count.c
	gcc -g p15-count.c -o p15-count

p17-writeafterend: p17-writeafterend.c
	gcc -g p17-writeafterend.c -o p17-writeafterend

p19-readwriteclose: p19-readwriteclose.c
	gcc -g p19-readwriteclose.c -o p19-readwriteclose

p21-buffeffect:	p21-buffeffect.c
	gcc -g p21-buffeffect.c -o p21-buffeffect

p25-filecontrol: p25-filecontrol.c
	gcc -g p25-filecontrol.c -o p25-filecontrol

p27-dupdup2: p27-dupdup2.c
	gcc -g p27-dupdup2.c -o p27-dupdup2

p33-samplestat: p33-samplestat.c
	gcc -g p33-samplestat.c -o p33-samplestat

p36-openreadclosedir: p36-openreadclosedir.c
	gcc -g p36-openreadclosedir.c -o p36-openreadclosedir

p38-morewithls: p38-morewithls.c
	gcc -g p38-morewithls.c -o p38-morewithls

